# Generated by Django 5.0.7 on 2024-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('button', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кнопка')),
                ('picture', models.ImageField(upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
