# Generated by Django 4.2.7 on 2024-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button',
            field=models.CharField(default=None, max_length=100, verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
