# Generated by Django 4.2.7 on 2024-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider_button_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Кнопка'),
        ),
    ]
