# Generated by Django 4.2.7 on 2023-12-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('vid_sv', models.CharField(max_length=30, verbose_name='Вид светильника')),
                ('tip_mon', models.CharField(max_length=30, verbose_name='Тип монтажа')),
                ('max_power', models.CharField(max_length=20, verbose_name='Максимальная мощность')),
                ('temp_sveta', models.CharField(max_length=20, verbose_name='Температура света')),
                ('svet_potok', models.CharField(max_length=20, verbose_name='Световой поток')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет корпуса')),
                ('svet', models.CharField(max_length=50, verbose_name='Свет')),
                ('srok', models.CharField(max_length=50, verbose_name='Срок службы')),
                ('size', models.CharField(max_length=100, verbose_name='Габариты')),
                ('napruga', models.CharField(max_length=100, verbose_name='Напржение питания')),
                ('protection', models.CharField(max_length=10, verbose_name='Степень защиты')),
                ('coef_puls', models.CharField(max_length=10, verbose_name='Коэффициент пульсации')),
                ('garant', models.CharField(max_length=10, verbose_name='Гарантия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='картинка')),
                ('url', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
